### ISSUE TITLE
Crash when return back from Gallery

### ISSUE THREAD

**Issue by SudaNix** [alhazmy13/MediaPicker#13]
When return back from Image Gallery without selecting any image, following crash happen:

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference

at net.alhazmy13.mediapicker.Image.ImageProcessing.processMultiImage(ImageProcessing.java:26)
at net.alhazmy13.mediapicker.Image.ImageActivity.onActivityResult(ImageActivity.java:204)

**Comment by alhazmy13** [comment]
i'll check it as soon as possible, Thx

**Comment by alhazmy13** [comment]
Fixed with version [2.2.4](https://github.com/alhazmy13/MediaPicker/pull/14)
Thank you
