### ISSUE TITLE
[BUG] NullPointException

### ISSUE THREAD

**Issue by 13120241790** [alhazmy13/MediaPicker#27]
FATAL EXCEPTION: AsyncTask #1
                                                          Process: com.jjjx, PID: 24263
                                                          java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                              at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                              at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                              at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                              at java.lang.Thread.run(Thread.java:818)
                                                           Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
                                                              at java.io.File.fixSlashes(File.java:183)
                                                              at java.io.File.<init>(File.java:130)
                                                              at net.alhazmy13.mediapicker.Video.VideoActivity$CompressImageTask.doInBackground(VideoActivity.java:343)
                                                              at net.alhazmy13.mediapicker.Video.VideoActivity$CompressImageTask.doInBackground(VideoActivity.java:315)
                                                              at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                              at java.lang.Thread.run(Thread.java:818)

**Comment by 13120241790** [comment]
This bug can repair? if you push to Jcenter , I wating for you!

**Comment by alhazmy13** [comment]
Hi @13120241790 

Are you using a custom directory or the default one? 
Try with this property `.directory(VideoPicker.Directory.DEFAULT)` and let me know if it solves your problem or not.
