### ISSUE TITLE
App crashes when you select an image from Google Drive

### ISSUE THREAD

**Issue by ankurgecr** [alhazmy13/MediaPicker#39]
Try to pick an image from Google Driver with following config:

```
new ImagePicker.Builder(MainActivity.this)
                        .mode(ImagePicker.Mode.CAMERA_AND_GALLERY)
                        .compressLevel(ImagePicker.ComperesLevel.MEDIUM)
                        .scale(200, 200)
                        .allowMultipleImages(true)
                        .enableDebuggingMode(true)
                        .build();
```

Application crashes with following Crash log:

```
E/SensorManager: app getDefaultSensor SENSOR TYPE =8
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
   Process: com.myicetag.myicetag, PID: 18698
   java.lang.RuntimeException: An error occurred while executing doInBackground()
	   at android.os.AsyncTask$3.done(AsyncTask.java:309)
	   at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	   at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	   at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	   at java.lang.Thread.run(Thread.java:818)
	Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
	   at java.io.File.fixSlashes(File.java:183)
	   at java.io.File.<init>(File.java:130)
	   at net.alhazmy13.mediapicker.Image.ImageActivity$CompressImageTask.doInBackground(ImageActivity.java:345)
	   at net.alhazmy13.mediapicker.Image.ImageActivity$CompressImageTask.doInBackground(ImageActivity.java:317)
	   at android.os.AsyncTask$2.call(AsyncTask.java:295)
	   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
	   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
	   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
	   at java.lang.Thread.run(Thread.java:818) 
```

**Comment by ankurgecr** [comment]
I found the reason and solve the issue by modifying `ImageActivity.java` file :)

Kindly have a look [at this file](https://www.dropbox.com/s/8jcbpl98x6p5ggl/ImageActivity.java?dl=0) and compare with yours. 

Happy coding.

**Comment by alhazmy13** [comment]
Thanks @ankurgecr 
It's fixed https://github.com/alhazmy13/MediaPicker/commit/1a2d996f75bc82a8e38c33a6077de4b5dd2b62fa, and I'll deploy it with next version.
