### ISSUE TITLE
java.lang.OutOfMemoryErrorFatal Exception: java.lang.RuntimeException An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by mikemike396** [alhazmy13/MediaPicker#50]
Getting this crash -> 

```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:318)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
Caused by java.lang.OutOfMemoryError: Failed to allocate a 63701004 byte allocation with 16777216 free bytes and 44MB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:977)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:948)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
       at net.alhazmy13.mediapicker.Utility.compressAndRotateIfNeeded(Utility.java:94)
       at net.alhazmy13.mediapicker.Image.ImageActivity$CompressImageTask.doInBackground(ImageActivity.java:388)
       at net.alhazmy13.mediapicker.Image.ImageActivity$CompressImageTask.doInBackground(ImageActivity.java:351)
       at android.os.AsyncTask$2.call(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
```

Location -> 
Utility.java line 94
net.alhazmy13.mediapicker.Utility.compressAndRotateIfNeeded

Running this build ->  
`compile 'net.alhazmy13.MediaPicker:libary:2.4.0'`

![screen shot 2017-12-20 at 8 42 34 am](https://user-images.githubusercontent.com/14999806/34209860-d68a70da-e561-11e7-8a74-580429ff0215.png)

**Comment by alhazmy13** [comment]
Hi @mikemike396 
Can you please add this line to your manifest under applications tag `android:largeHeap="true"`

```java
  <application
      android:name=".ParaseApplication"
      android:allowBackup="true"
      android:icon="@mipmap/ic_launcher"
      android:label="@string/app_name"
      android:theme="@style/AppTheme"
      android:largeHeap="true" >
```

**Comment by mikemike396** [comment]
I added the larger heap setting to the manifest and redeployed. I will post back in a few days to see if it shows up again. Thanks again for the help!

**Comment by wisnukurniawan** [comment]
How the result bro @mikemike396 ?

**Comment by mikemike396** [comment]
@wisnukurniawan looking great so far! The crash hasn’t appeared in the new version yet.
