### ISSUE TITLE
No Activity to handle video Action_pick intent

### ISSUE THREAD

**Issue by JohnItoo** [alhazmy13/MediaPicker#58]
Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.PICK typ=video/* }
                                                                                 at 
       android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1781)
                                                                                 at 
    android.app.Instrumentation.execStartActivity(Instrumentation.java:1501)
                                                                                 at 
    android.app.Activity.startActivityForResult(Activity.java:3745)
                                                                                 at 
    android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
                                                                                 at 
    android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
                                                                                 at 
    android.app.Activity.startActivityForResult(Activity.java:3706)
                                                                                 at 
    android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:871)
                                                                                     at 
    net.alhazmy13.mediapicker.Video.VideoActivity.startActivityFromGallery(VideoActivity.java:108)
                                                                                 at 
    net.alhazmy13.mediapicker.Video.VideoActivity.pickVideo(VideoActivity.java:72)
                                                                                 at 
      net.alhazmy13.mediapicker.Video.VideoActivity.pickImageWrapper(VideoActivity.java:209)
                                                                                 at net.alhazmy13.mediapicker.Video.VideoActivity.onCreate(VideoActivity.java:60)
                                                                                 at android.app.Activity.performCreate(Activity.java:5990)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:135) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)

**Comment by alhazmy13** [comment]
Hi @JohnItoo 
Can you please confirm if it fixed wit last beta release [2.4.1-beta](https://github.com/alhazmy13/MediaPicker/releases/tag/2.4.1-beta) or not?

Thanks

**Comment by JohnItoo** [comment]
Sorry @alhazmy13  . I am not using your library on the product anymore. If I can 
I would help check it
