### ISSUE TITLE
Only fullscreen opaque activities can request orientation Android 8

### ISSUE THREAD

**Issue by SerhiiSolobaievUptech** [alhazmy13/MediaPicker#64]
`Caused by java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
       at android.app.Activity.onCreate(Activity.java:1038)
       at android.support.v4.app.SupportActivity.onCreate(SupportActivity.java:66)
       at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:297)
       at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
       at net.alhazmy13.mediapicker.Image.ImageActivity.onCreate(ImageActivity.java:56)
       at android.app.Activity.performCreate(Activity.java:7174)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

**Comment by pezezzle** [comment]
I have the same Problem. is a Solution avilable ?

**Comment by SerhiiSolobaievUptech** [comment]
@pezezzle not yet :(

**Comment by alhazmy13** [comment]
Hi @SerhiiSolobaievUptech and @pezezzle 
Can you please confirm if it fixed wit last beta release [2.4.1-beta](https://github.com/alhazmy13/MediaPicker/releases/tag/2.4.1-beta) or not?

Thanks

**Comment by SerhiiSolobaievUptech** [comment]
@alhazmy13 Yes, `Gallery` works but for `Camera` I have this crash 😢 
`java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
                                                                           at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:604)
                                                                           at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:578)
                                                                           at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:416)
                                                                           at net.alhazmy13.mediapicker.Image.ImageActivity.startActivityFromCamera(ImageActivity.java:168)
                                                                           at net.alhazmy13.mediapicker.Image.ImageActivity.access$400(ImageActivity.java:45)
                                                                           at net.alhazmy13.mediapicker.Image.ImageActivity$3.onClick(ImageActivity.java:111)
                                                                           at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                           at android.os.Looper.loop(Looper.java:164)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by alhazmy13** [comment]
@SerhiiSolobaievUptech Good, Let'screet another issue and close this one, i'll fix it with another beta version.

**Comment by pezezzle** [comment]
@alhazmy13  for me works with `Gallery` and `Camera` fine.
Thanks a Lot.

**Comment by SerhiiSolobaievUptech** [comment]
Thank you!

**Comment by alhazmy13** [comment]
@SerhiiSolobaievUptech Version 2.4.2-beta is live now, can you please test it?

**Comment by SerhiiSolobaievUptech** [comment]
@alhazmy13 still have the same crash when clicking on `Camera`. Test device - Samsung S9 with Android 8.0

**Comment by alhazmy13** [comment]
@SerhiiSolobaievUptech Weird, Can you please clone dev branch and test app module on your device?
I need to know if this crash from your application or form MediaPicker.

--  I'll try to test it with Samsung device.

**Comment by SerhiiSolobaievUptech** [comment]
@alhazmy13 Tested your dev branch and everything works. Seems that the problem is when app uses other providers (in my case it is `FreshchatProvider`)
`<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.freshchatProvider"
            android:exported="false"
            android:grantUriPermissions="true"
            tools:replace="android:authorities">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/freshchat_file_provider_paths"
                tools:replace="android:resource" />
        </provider>`

**Comment by SerhiiSolobaievUptech** [comment]
@alhazmy13 Hey, did you have a chance to check why it crashes when we have other providers?

**Comment by SerhiiSolobaievUptech** [comment]
Fixed by creating new FreshchatProvider class
