### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.AlertDialog.isShowing()' on a null object reference

### ISSUE THREAD

**Issue by SerhiiSolobaievUptech** [alhazmy13/MediaPicker#67]
`Process: com.sprent.customer.dev, PID: 24189
                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.AlertDialog.isShowing()' on a null object reference
                                                                             at net.alhazmy13.mediapicker.Image.ImageActivity.onSaveInstanceState(ImageActivity.java:182)
                                                                             at android.app.Activity.performSaveInstanceState(Activity.java:1302)
                                                                             at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1289)
                                                                             at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4088)
                                                                             at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3490)
                                                                             at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3550)
                                                                             at android.app.ActivityThread.-wrap20(ActivityThread.java)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by SerhiiSolobaievUptech** [comment]
@alhazmy13 Hello, any updates on this issue?

**Comment by modyking55** [comment]
Any Reply

**Comment by SerhiiSolobaievUptech** [comment]
@alhazmy13 hey, this is #1 crash in my app now. Can you please try to fix it?)

**Comment by Saecun** [comment]
@SerhiiSolobaievUptech / @modyking55  - the code on master has changed recently, so I cannot provide a pull request, however, I have a repo with an update that fixes it for me 

https://github.com/Saecun/MediaPicker/releases/tag/2.4.1a-beta

`implementation 'com.github.saecun:MediaPicker:2.4.1a-beta'`

**Comment by SerhiiSolobaievUptech** [comment]
@Saecun thanks!
@alhazmy13 plz make a change to get this fix. It's really important to make your library better than it is :)

**Comment by SerhiiSolobaievUptech** [comment]
Created PR: https://github.com/alhazmy13/MediaPicker/pull/78
Very huge PR 😂

**Comment by alhazmy13** [comment]
Fixed with [Version 2.4.4](https://github.com/alhazmy13/MediaPicker/releases/tag/2.4.4) 
Thanks @SerhiiSolobaievUptech
