### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.alhazmy13.mediapicker.Image.ImageActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation on Android 8

### ISSUE THREAD

**Issue by RoberV** [alhazmy13/MediaPicker#68]
Hi, there is a problem with ANdorid 8, when you try to start ImageActivity it throws thi sexception:

`ava.lang.RuntimeException: Unable to start activity ComponentInfo{net.alhazmy13.mediapicker.Image.ImageActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
        at android.app.Activity.onCreate(Activity.java:986)
        at android.support.v4.app.SupportActivity.onCreate(SupportActivity.java:66)
        at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:297)
        at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
        at net.alhazmy13.mediapicker.Image.ImageActivity.onCreate(ImageActivity.java:61)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) `

**Comment by alhazmy13** [comment]
Fixed with [Version 2.4.4](https://github.com/alhazmy13/MediaPicker/releases/tag/2.4.4) 
Thanks
