### ISSUE TITLE
NullPointerException ImageActivity:397 When selecting from Google Photos

### ISSUE THREAD

**Issue by Innova133** [alhazmy13/MediaPicker#92]
Version 2.4.4

Starting up like this:

                                ImagePicker.Builder(activity)
                                        .mode(ImagePicker.Mode.CAMERA_AND_GALLERY)
                                        .allowMultipleImages(true)
                                        .enableDebuggingMode(true)
                                        .allowOnlineImages(true)
                                        .build()

It depends on which images I select, but if I go:  
Hamburger Menu->Photos->Photos->Pick one of the "stylized" photos the app will crash with the following stack trace.   Attached image shows debugger with breakpoint.
<img width="1339" alt="debugging" src="https://user-images.githubusercontent.com/3246186/50672972-be18ef80-0fa0-11e9-81a5-715259b2e5a0.png">

2019-01-03 21:38:21.435 8255-8632/com.thenextbite.prochatter.test E/UncaughtException: java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NullPointerException
        at java.io.File.<init>(File.java:283)
        at net.alhazmy13.mediapicker.Image.ImageActivity$CompressImageTask.doInBackground(ImageActivity.java:397)
        at net.alhazmy13.mediapicker.Image.ImageActivity$CompressImageTask.doInBackground(ImageActivity.java:369)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by Innova133** [comment]
Video showing it working and crashing:   https://youtu.be/4xSIOoARZdY
